dist: xenial   # required for Python >= 3.7
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - buildout
script:
# The test actually is empty at the moment.
  - ./bin/test
# But buildout has installed a really basic supervisor that we should be able to use.
  - ./bin/supervisord
  - ./bin/supervisorctl status
  - ./bin/supervisorctl shutdown
