language: python
python:
  - "3.10"
  - "3.11"
  - "3.12"
  - "3.13"
install:
  - virtualenv .
  - bin/pip install -r requirements.txt
  - bin/buildout
script:
# The test actually is empty at the moment.
  - ./bin/test
# But buildout has installed a really basic supervisor that we should be able to use.
  - ./bin/supervisord
  - ./bin/supervisorctl status
  - ./bin/supervisorctl shutdown
